# neoforge.mods.toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader
loaderVersion="[4.0,)"
# The license for you mod
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/TWheatKing/Enerjolt/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="enerjolt"
# The version number of the mod
version="1.21.1-0.0.1-neoforge"
# A display name for the mod
displayName="Enerjolt"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/TWheatKing/Enerjolt"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png"
# A text field displayed in the mod UI
credits="Thanks to Kaupenjoe for the tutorials in modding Minecraft. Also thanks to Claude.ai for bug fixes and improvements"
# A text field displayed in the mod UI
authors="TWheatKing"

# The description text for the mod (multi line!)
description='''Enerjolt - More than just energy and automation, NEW mobs, biome and dimension for Minecraft 1.21.1'''

# Dependencies
[[dependencies.enerjolt]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enerjolt]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enerjolt]]
modId = "terrablender"
mandatory = true
versionRange = "[4.1.0.8,)"
ordering = "NONE"
side = "BOTH"